<?php

namespace TheWebmen\Formbuilder\Fields;

use SilverStripe\ORM\ArrayList;
use SilverStripe\View\ArrayData;

class ModelDropdownField extends \SilverStripe\Forms\DropdownField
{
    private $_overrideValidator = false;

    public function setOverrideValidator($bool)
    {
        $this->overrideValidator = $bool;
    }

    public function getOverrideValidator()
    {
        return $this->overrideValidator;
    }

    public function validate($validator)
    {
        if (!$this->overrideValidator)
            return parent::validate($validator); // TODO: Change the autogenerated stub
        else
            return true;
    }

    public static function get_allowed_models()
    {
        $models = self::get_config_data()->get('models');

        $return = ArrayList::create();

        foreach ($models as $model)
        {
            $model = reset($model);
            $return->push(new ArrayData(['class' => $model['class'], 'name' => (new $model['class']())->plural_name()]));
        }

        return $return;
    }

    public static function get_config_data()
    {
        return self::config();
    }

    public static function get_frontend_javascript()
    {
        $extraScript = <<<EOS
<script type="text/javascript">
    $(function()
    {
        $('option', '[data-relation-dropdown=parent]').each(function()
        {
            var id = $(this).val();
            $(this).val($(this).text()).data('id', id);
        });
        
        $('[data-relation-dropdown=parent]').on('change', function(evt)
        {
            var id = $('option:selected', this).data('id');
            var model = $(this).data('data');
            
            var child = $('[data-relation-dropdown=child][data-data='+model+']');
            $(child).empty();
            $(window[model][id]).each(function()
            {
                $('<option>').val(this.Key).text(this.Value).appendTo(child);
            });
        });
    });
</script>
EOS;

        return $extraScript;
    }

}